definitions:
  request.CreateCommentRequest:
    properties:
      content:
        type: string
      parent_id:
        type: integer
    type: object
  response.CommentTreeResponse:
    properties:
      children:
        items:
          $ref: '#/definitions/response.CommentTreeResponse'
        type: array
      content:
        type: string
      created_at:
        type: string
      depth:
        type: integer
      id:
        type: integer
      parent_id:
        type: integer
    type: object
  response.CreateCommentResponse:
    properties:
      content:
        example: nice picture!!!
        type: string
      created_at:
        example: "2026-02-02T14:31:00Z"
        type: string
      id:
        example: 12
        type: integer
      parent_id:
        example: 1
        type: integer
    type: object
  response.Error:
    properties:
      error:
        example: invalid request body
        type: string
    type: object
  response.PaginatedCommentsResponse:
    properties:
      comments:
        items:
          $ref: '#/definitions/response.CommentTreeResponse'
        type: array
      limit:
        type: integer
      offset:
        type: integer
      page:
        type: integer
      pages:
        type: integer
      total:
        type: integer
    type: object
info:
  contact: {}
paths:
  /v1/comments:
    get:
      description: Get comment(s) with all replies, search, sort
      parameters:
      - description: Parent ID
        in: query
        name: parent_id
        type: string
      - description: Search text
        in: query
        name: search
        type: string
      - description: Sort option
        enum:
        - created_at
        - id
        in: query
        name: sort_by
        type: string
      - description: Sort order
        enum:
        - asc
        - ASC
        - desc
        - DESC
        in: query
        name: order
        type: string
      - description: Limit of comments on one page, default 20
        in: query
        name: limit
        type: string
      - description: Offset for displaying a specific page, default 0
        in: query
        name: offset
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.PaginatedCommentsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      summary: Get comments
      tags:
      - comments
    post:
      consumes:
      - application/json
      description: Creates new comment
      parameters:
      - description: Comment
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.CreateCommentRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.CreateCommentResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      summary: Create new comment
      tags:
      - comments
swagger: "2.0"
